typedef struct listcreator NODE ;
int newlist(NODE **Head) ; 
int dellist(NODE **Head ) ; 
int filllist(  int len  , int value , NODE **Head ) ;
int append( int elem ,  NODE **Head ) ;
int setlist( int arr[] , NODE **Head ) ; 
int insert(int elem, int index,  NODE **Head ) ;
int length(NODE **Head) ; 
long long int sum(NODE **Head) ; 
int getitem(int index ,NODE **Head) ; 
int pop(NODE **Head) ; 
int count(int key , NODE **Head) ; 
int removeitem(int key , NODE **Head) ;
int indexlist(int key , NODE **Head) ;  
void reverselist(NODE **Head) ; 
void printlist( NODE **Start ) ; 
